# Generated by Django 4.2.17 on 2025-02-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_book_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_views_all_borrowed_books', 'For Staff account Login can views all Borrowed Books'),)},
        ),
    ]
